name: Push to Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout Target Repository
      run: |
        git remote add target http://${{ github.actor }}:${{ secrets.TOKEN_GITHUB }}@github.com/${{ secrets.TARGET_REPOSITORY }}.git
        git fetch target
        git checkout -b ${{ secrets.TARGET_BRANCH }} target/${{ secrets.TARGET_BRANCH }}
    - name: Config Git
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
    - name: Commit forward submodules
      run: |
        git submodule init
        git submodule update --recursive --remote
        git add .
        git commit -m 'Update submodules'
    - name: Push commit
      run: |
        git push -u target ${{ secrets.TARGET_BRANCH }}
